### ISSUE TITLE
Watch incoming directories issue

### ISSUE THREAD

**Issue by neogamaes** [pixeltech42/PTorrent#3]
Hello,

The "Watch incoming directories" does not work properly on my android device.

If I put a torrent file in the "watch directory" the download does not start automatically. If I start the download manually by browsing into the "watch directory" and then delete the download (data only) which I just started, the download will start again automatically... It seems I have to show the path once to make the "watch incoming directories" work.

Unfortunately, if I put another torrent file in the "watch incoming directory" the automatic download still not start unless I do it manually.

Can you help me ?

Thank you,

**Comment by pixeltech42** [comment]
it is fixed in 1.7.8
